local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.05

  static_map: false  
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.05
  
